// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OncoGuard.Infrastructure.Persistence;

#nullable disable

namespace OncoGuard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OncoGuard.Domain.Entities.AlertNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("RiskScoreId")
                        .HasColumnType("int");

                    b.Property<int>("RiskType")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<bool>("TriggeredByModel")
                        .HasColumnType("bit");

                    b.Property<bool>("TriggeredByRule")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RiskScoreId");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.CalculatedFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("AlbuminTrend")
                        .HasColumnType("float");

                    b.Property<double?>("AltTrend")
                        .HasColumnType("float");

                    b.Property<double?>("AncTrend")
                        .HasColumnType("float");

                    b.Property<bool>("AntibioticUseFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("AntiemeticUseFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("AppetiteTrend7Day")
                        .HasColumnType("float");

                    b.Property<double?>("AstTrend")
                        .HasColumnType("float");

                    b.Property<double?>("BilirubinTrend")
                        .HasColumnType("float");

                    b.Property<double?>("CalorieDeficit7Day")
                        .HasColumnType("float");

                    b.Property<double?>("CalorieRatio")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CreatinineTrend")
                        .HasColumnType("float");

                    b.Property<double?>("CrpAlbuminRatio")
                        .HasColumnType("float");

                    b.Property<bool>("CrpIncreaseFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("DiarrheaTrend")
                        .HasColumnType("float");

                    b.Property<double?>("DizzinessDryMouthScore")
                        .HasColumnType("float");

                    b.Property<double?>("DyspneaTrend")
                        .HasColumnType("float");

                    b.Property<bool>("EgfrDropFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("ElectrolyteImbalanceScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("FeatureDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FeverAndLowAncFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("FeverFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("FreeT4AbnormalFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("FunctionalDeclineScore")
                        .HasColumnType("float");

                    b.Property<double?>("InfectionSymptomScore")
                        .HasColumnType("float");

                    b.Property<int?>("LabCycleId")
                        .HasColumnType("int");

                    b.Property<double?>("LymphocyteTrend")
                        .HasColumnType("float");

                    b.Property<int?>("MealSkippingFrequency")
                        .HasColumnType("int");

                    b.Property<double?>("MedicationAdherenceScore")
                        .HasColumnType("float");

                    b.Property<int?>("MissedDoseCount3Day")
                        .HasColumnType("int");

                    b.Property<int?>("MissedDoseCount7Day")
                        .HasColumnType("int");

                    b.Property<int>("MissingLogCount3Day")
                        .HasColumnType("int");

                    b.Property<int>("MissingLogCount7Day")
                        .HasColumnType("int");

                    b.Property<bool>("MissingMedicationFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("MissingNutritionFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("MissingSymptomFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("PatientBurdenScore")
                        .HasColumnType("float");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<bool>("PreviousNeutropeniaFlag")
                        .HasColumnType("bit");

                    b.Property<double?>("ProteinDeficit3Day")
                        .HasColumnType("float");

                    b.Property<double?>("ProteinDeficit7Day")
                        .HasColumnType("float");

                    b.Property<double?>("ProteinRatio")
                        .HasColumnType("float");

                    b.Property<double?>("SkinRashTrend")
                        .HasColumnType("float");

                    b.Property<bool>("SteroidUseFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("TshAbnormalFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UreaCreatinineRatio")
                        .HasColumnType("float");

                    b.Property<double?>("VomitingDiarrheaFluidLossScore")
                        .HasColumnType("float");

                    b.Property<double?>("WaterRatio")
                        .HasColumnType("float");

                    b.Property<double?>("WbcTrend")
                        .HasColumnType("float");

                    b.Property<double?>("WeightLoss30DayPercent")
                        .HasColumnType("float");

                    b.Property<double?>("WeightLoss7DayPercent")
                        .HasColumnType("float");

                    b.Property<double?>("WeightLoss90DayPercent")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LabCycleId");

                    b.HasIndex("PatientId");

                    b.ToTable("CalculatedFeatures");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.CancerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlcoholStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CancerType")
                        .HasColumnType("int");

                    b.Property<string>("Comorbidities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiagnosisDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EcogPerformanceScore")
                        .HasColumnType("int");

                    b.Property<bool>("HasMetastasis")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("SmokingStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentGoal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("CancerProfiles");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.CancerTypeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CancerType")
                        .HasColumnType("int");

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHighCachexiaRisk")
                        .HasColumnType("bit");

                    b.Property<string>("RecommendedLabPanel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresFrequentInfectionMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresHydrationMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresImmunotherapyMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresNutritionMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresPulmonaryMonitoring")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CancerTypeConfigs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.ClinicalReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GeneratedByAI")
                        .HasColumnType("bit");

                    b.Property<int?>("LabCycleId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReviewedByDoctor")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LabCycleId");

                    b.HasIndex("PatientId");

                    b.ToTable("ClinicalReports");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneralConditionScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMissingLog")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.FoodLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AmountGram")
                        .HasColumnType("float");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrate")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<double?>("Fiber")
                        .HasColumnType("float");

                    b.Property<double?>("Folate")
                        .HasColumnType("float");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Iron")
                        .HasColumnType("float");

                    b.Property<double?>("Magnesium")
                        .HasColumnType("float");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double?>("Selenium")
                        .HasColumnType("float");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("VitaminB12")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminD")
                        .HasColumnType("float");

                    b.Property<double?>("Zinc")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId");

                    b.ToTable("FoodLogs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "İstanbul Onkoloji Hastanesi"
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medipol Hastanesi"
                        },
                        new
                        {
                            Id = 3,
                            City = "İstanbul",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acıbadem Hastanesi"
                        });
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.HydrationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<int>("DryMouth")
                        .HasColumnType("int");

                    b.Property<bool>("HasDizziness")
                        .HasColumnType("bit");

                    b.Property<bool>("HasVomitingOrDiarrhea")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UrinationCount")
                        .HasColumnType("int");

                    b.Property<string>("UrineColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WaterIntakeMl")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId")
                        .IsUnique();

                    b.ToTable("HydrationLogs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.LabCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaselineLabId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CycleSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousCycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BaselineLabId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PreviousCycleId");

                    b.ToTable("LabCycles");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.LabResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("Albumin")
                        .HasColumnType("float");

                    b.Property<double?>("Alp")
                        .HasColumnType("float");

                    b.Property<double?>("Alt")
                        .HasColumnType("float");

                    b.Property<double?>("Amylase")
                        .HasColumnType("float");

                    b.Property<double?>("Anc")
                        .HasColumnType("float");

                    b.Property<double?>("Ast")
                        .HasColumnType("float");

                    b.Property<double?>("Calcium")
                        .HasColumnType("float");

                    b.Property<double?>("Chloride")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Creatinine")
                        .HasColumnType("float");

                    b.Property<double?>("Crp")
                        .HasColumnType("float");

                    b.Property<double?>("DirectBilirubin")
                        .HasColumnType("float");

                    b.Property<double?>("Egfr")
                        .HasColumnType("float");

                    b.Property<double?>("Esr")
                        .HasColumnType("float");

                    b.Property<double?>("Ferritin")
                        .HasColumnType("float");

                    b.Property<double?>("Folate")
                        .HasColumnType("float");

                    b.Property<double?>("FreeT4")
                        .HasColumnType("float");

                    b.Property<double?>("Ggt")
                        .HasColumnType("float");

                    b.Property<double?>("Glucose")
                        .HasColumnType("float");

                    b.Property<double?>("Hematocrit")
                        .HasColumnType("float");

                    b.Property<double?>("Hemoglobin")
                        .HasColumnType("float");

                    b.Property<double?>("Iron")
                        .HasColumnType("float");

                    b.Property<DateTime>("LabDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Ldh")
                        .HasColumnType("float");

                    b.Property<double?>("Lipase")
                        .HasColumnType("float");

                    b.Property<double?>("Lymphocyte")
                        .HasColumnType("float");

                    b.Property<double?>("Magnesium")
                        .HasColumnType("float");

                    b.Property<double?>("Mcv")
                        .HasColumnType("float");

                    b.Property<double?>("Monocyte")
                        .HasColumnType("float");

                    b.Property<double?>("MorningCortisol")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<double?>("Platelet")
                        .HasColumnType("float");

                    b.Property<double?>("Potassium")
                        .HasColumnType("float");

                    b.Property<double?>("Prealbumin")
                        .HasColumnType("float");

                    b.Property<double?>("Procalcitonin")
                        .HasColumnType("float");

                    b.Property<double?>("Rdw")
                        .HasColumnType("float");

                    b.Property<double?>("Selenium")
                        .HasColumnType("float");

                    b.Property<double?>("Sodium")
                        .HasColumnType("float");

                    b.Property<double?>("TotalBilirubin")
                        .HasColumnType("float");

                    b.Property<double?>("TotalProtein")
                        .HasColumnType("float");

                    b.Property<double?>("TransferrinSaturation")
                        .HasColumnType("float");

                    b.Property<double?>("Tsh")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Urea")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminB12")
                        .HasColumnType("float");

                    b.Property<double?>("VitaminD")
                        .HasColumnType("float");

                    b.Property<double?>("Wbc")
                        .HasColumnType("float");

                    b.Property<double?>("Zinc")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("LabResults");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.MedicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<bool>("HadSideEffect")
                        .HasColumnType("bit");

                    b.Property<int>("MissedDoseCount")
                        .HasColumnType("int");

                    b.Property<string>("SideEffectDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TookMainMedication")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsedAntibiotic")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedAntiemetic")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedPainkiller")
                        .HasColumnType("bit");

                    b.Property<bool>("UsedSteroid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId")
                        .IsUnique();

                    b.ToTable("MedicationLogs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.ModelVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatasetVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TrainingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("ValidationAccuracy")
                        .HasColumnType("float");

                    b.Property<double?>("ValidationF1Score")
                        .HasColumnType("float");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModelVersions");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.NutritionSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CalorieRatio")
                        .HasColumnType("float");

                    b.Property<double>("CalorieTarget")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCalorieDeficient")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProteinDeficient")
                        .HasColumnType("bit");

                    b.Property<double>("MealCompletionRatio")
                        .HasColumnType("float");

                    b.Property<double>("ProteinRatio")
                        .HasColumnType("float");

                    b.Property<double>("ProteinTarget")
                        .HasColumnType("float");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("float");

                    b.Property<double>("TotalCarbohydrate")
                        .HasColumnType("float");

                    b.Property<double>("TotalFat")
                        .HasColumnType("float");

                    b.Property<double>("TotalProtein")
                        .HasColumnType("float");

                    b.Property<double>("TotalWaterMl")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId")
                        .IsUnique();

                    b.ToTable("NutritionSummaries");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CancerType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("HospitalId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.RiskExplanation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ContributionScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExplanationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExplanationTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimaryReason")
                        .HasColumnType("bit");

                    b.Property<int>("RiskScoreId")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RiskScoreId");

                    b.ToTable("RiskExplanations");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.RiskScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Confidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("bit");

                    b.Property<int?>("LabCycleId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresDoctorReview")
                        .HasColumnType("bit");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.Property<int>("RiskType")
                        .HasColumnType("int");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LabCycleId");

                    b.HasIndex("PatientId");

                    b.ToTable("RiskScores");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.RiskWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CancerType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RiskType")
                        .HasColumnType("int");

                    b.Property<int?>("TreatmentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("WeightValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RiskWeights");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doctor"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Patient"
                        });
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.SymptomLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BodyTemperature")
                        .HasColumnType("float");

                    b.Property<int>("Constipation")
                        .HasColumnType("int");

                    b.Property<int>("Cough")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<int>("DiarrheaCount")
                        .HasColumnType("int");

                    b.Property<int>("Dyspnea")
                        .HasColumnType("int");

                    b.Property<int>("Fatigue")
                        .HasColumnType("int");

                    b.Property<bool>("HasBleedingOrBruising")
                        .HasColumnType("bit");

                    b.Property<bool>("HasConfusion")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDizziness")
                        .HasColumnType("bit");

                    b.Property<int>("MouthSore")
                        .HasColumnType("int");

                    b.Property<int>("Nausea")
                        .HasColumnType("int");

                    b.Property<string>("OtherSymptoms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pain")
                        .HasColumnType("int");

                    b.Property<int>("SkinRash")
                        .HasColumnType("int");

                    b.Property<int>("SwallowingDifficulty")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VomitingCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId")
                        .IsUnique();

                    b.ToTable("SymptomLogs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.TreatmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("int");

                    b.Property<bool>("HadPreviousTreatmentDelay")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDoseReduction")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPreviousNeutropenia")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastTreatmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextPlannedTreatmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ProtocolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreatmentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UsesAntibiotic")
                        .HasColumnType("bit");

                    b.Property<bool>("UsesAntiemetic")
                        .HasColumnType("bit");

                    b.Property<bool>("UsesGcsfSupport")
                        .HasColumnType("bit");

                    b.Property<bool>("UsesPainkiller")
                        .HasColumnType("bit");

                    b.Property<bool>("UsesSteroid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.TreatmentTypeConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClinicalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasHighCachexiaRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHighDehydrationRisk")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHighNeutropeniaRisk")
                        .HasColumnType("bit");

                    b.Property<string>("RecommendedSupportiveCare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresCardiacMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresEndocrineMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresInfectionMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresKidneyMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresLiverMonitoring")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiresPulmonaryMonitoring")
                        .HasColumnType("bit");

                    b.Property<int>("TreatmentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TreatmentTypeConfigs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.VitalSignsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("BodyTemperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DailyLogId")
                        .HasColumnType("int");

                    b.Property<double?>("DiastolicBloodPressure")
                        .HasColumnType("float");

                    b.Property<double?>("HeartRate")
                        .HasColumnType("float");

                    b.Property<double?>("OxygenSaturation")
                        .HasColumnType("float");

                    b.Property<double?>("SystolicBloodPressure")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DailyLogId")
                        .IsUnique();

                    b.ToTable("VitalSignsLogs");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.AlertNotification", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OncoGuard.Domain.Entities.RiskScore", "RiskScore")
                        .WithMany()
                        .HasForeignKey("RiskScoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");

                    b.Navigation("RiskScore");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.CalculatedFeature", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.LabCycle", "LabCycle")
                        .WithMany()
                        .HasForeignKey("LabCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabCycle");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.CancerProfile", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.ClinicalReport", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.LabCycle", "LabCycle")
                        .WithMany()
                        .HasForeignKey("LabCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabCycle");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.DailyLog", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OncoGuard.Domain.Entities.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("OncoGuard.Domain.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.FoodLog", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.DailyLog", "DailyLog")
                        .WithMany()
                        .HasForeignKey("DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.HydrationLog", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.DailyLog", "DailyLog")
                        .WithOne()
                        .HasForeignKey("OncoGuard.Domain.Entities.HydrationLog", "DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.LabCycle", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.LabResult", "BaselineLab")
                        .WithMany()
                        .HasForeignKey("BaselineLabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OncoGuard.Domain.Entities.LabCycle", "PreviousCycle")
                        .WithMany()
                        .HasForeignKey("PreviousCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaselineLab");

                    b.Navigation("Patient");

                    b.Navigation("PreviousCycle");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.LabResult", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.MedicationLog", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.DailyLog", "DailyLog")
                        .WithOne()
                        .HasForeignKey("OncoGuard.Domain.Entities.MedicationLog", "DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.NutritionSummary", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.DailyLog", "DailyLog")
                        .WithOne()
                        .HasForeignKey("OncoGuard.Domain.Entities.NutritionSummary", "DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Patient", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Patients")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OncoGuard.Domain.Entities.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OncoGuard.Domain.Entities.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("OncoGuard.Domain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Hospital");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.RiskExplanation", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.RiskScore", "RiskScore")
                        .WithMany()
                        .HasForeignKey("RiskScoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RiskScore");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.RiskScore", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.LabCycle", "LabCycle")
                        .WithMany()
                        .HasForeignKey("LabCycleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabCycle");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.SymptomLog", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.DailyLog", "DailyLog")
                        .WithOne()
                        .HasForeignKey("OncoGuard.Domain.Entities.SymptomLog", "DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.TreatmentPlan", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.User", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.VitalSignsLog", b =>
                {
                    b.HasOne("OncoGuard.Domain.Entities.DailyLog", "DailyLog")
                        .WithOne()
                        .HasForeignKey("OncoGuard.Domain.Entities.VitalSignsLog", "DailyLogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DailyLog");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("OncoGuard.Domain.Entities.User", b =>
                {
                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
